### ISSUE TITLE
CT assertion failed item not found in array

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/fractions-mixed-numbers#11] opened 2021-03-18 18:31 UTC
```
fractions-mixed-numbers : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1616082139562/fractions-mixed-numbers/fractions-mixed-numbers_en.html?continuousTest=%7B%22test%22%3A%5B%22fractions-mixed-numbers%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1616082139562%22%2C%22timestamp%22%3A1616084897486%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught Error: Assertion failed
Error: Assertion failed
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1616082139562/assert/js/assert.js:25:13)
at CircularSceneNode.getBucketPosition (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1616082139562/fractions-common/js/intro/view/ContainerSetScreenView.js:98:17)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1616082139562/fractions-common/js/intro/view/CellSceneNode.js:222:54
at DragListener.end [as _end] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1616082139562/fractions-common/js/intro/view/PieceNode.js:81:18)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1616082139562/scenery/js/listeners/DragListener.js:337:25
at DragListener.onRelease (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1616082139562/scenery/js/listeners/PressListener.js:646:17)
at Action.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1616082139562/axon/js/Action.js:225:18)
at DragListener.release (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1616082139562/scenery/js/listeners/PressListener.js:427:25)
at DragListener.release (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1616082139562/scenery/js/listeners/DragListener.js:333:11)
at DragListener.pointerUp (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1616082139562/scenery/js/listeners/PressListener.js:757:12)
id: Bayes Chrome
Snapshot from 3/18/2021, 9:42:19 AM

----------------------------------

fractions-mixed-numbers : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1616082139562/fractions-mixed-numbers/fractions-mixed-numbers_en.html?continuousTest=%7B%22test%22%3A%5B%22fractions-mixed-numbers%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1616082139562%22%2C%22timestamp%22%3A1616083495665%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught Error: Assertion failed: item not found in Array
Error: Assertion failed: item not found in Array
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1616082139562/assert/js/assert.js:25:13)
at arrayRemove (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1616082139562/phet-core/js/arrayRemove.js:19:13)
at Proxy.remove (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1616082139562/axon/js/createObservableArray.js:345:33)
at IntroModel.completePiece (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1616082139562/fractions-common/js/intro/model/ContainerSetModel.js:160:17)
at IntroModel.emptyNextCell (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1616082139562/fractions-common/js/intro/model/ContainerSetModel.js:227:16)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1616082139562/fractions-common/js/intro/model/ContainerSetModel.js:324:14
at baseTimes (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1616082139562/sherpa/lib/lodash-4.17.4.js:997:23)
at Function.times (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1616082139562/sherpa/lib/lodash-4.17.4.js:16095:20)
at IntroModel.onNumeratorChange (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1616082139562/fractions-common/js/intro/model/ContainerSetModel.js:319:7)
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1616082139562/axon/js/TinyEmitter.js:86:18)
id: Bayes Chrome
Snapshot from 3/18/2021, 9:42:19 AM
```

**Comment by marlitas** [comment] 2023-09-22 21:45
This looks like a duplicate of https://github.com/phetsims/fractions-common/issues/112. Closing as such.

**Closed as completed by marlitas** 2023-09-22 21:45 UTC
Labels: type:automated-testing
